ur5_robotiq_joint_limited:

  #Publish all joint states
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50
    
  #Position Controllers
  shoulder_pan_joint_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_pan_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  shoulder_lift_joint_controller:
    type: effort_controllers/JointPositionController
    joint: shoulder_lift_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  elbow_joint_controller:
    type: effort_controllers/JointPositionController
    joint: elbow_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  wrist_1_joint_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_1_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  wrist_2_joint_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_2_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  wrist_3_joint_controller:
    type: effort_controllers/JointPositionController
    joint: wrist_3_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  ee_fixed_joint_controller:
    type: effort_controllers/JointPositionController
    joint: ee_fixed_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_base_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_base_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_left_knuckle_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_left_knuckle_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_right_knuckle_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_right_knuckle_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_left_finger_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_left_finger_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_right_finger_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_right_finger_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_left_inner_knuckle_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_left_inner_knuckle_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_right_inner_knuckle_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_right_inner_knuckle_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_left_finger_tip_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_left_finger_tip_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}
  robotiq_85_right_finger_joint_controller:
    type: effort_controllers/JointPositionController
    joint: robotiq_85_right_finger_tip_joint
    pid: {p: 1000.0, i: 0.01, d: 10.0}