controller_list:
  - name: fake_arm_controller
    type: "position_controllers/JointTrajectoryController"
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - ee_fixed_joint
      - robotiq_85_base_joint
      - robotiq_85_left_knuckle_joint
      - robotiq_85_right_knuckle_joint
      - robotiq_85_left_finger_joint
      - robotiq_85_right_finger_joint
      - robotiq_85_left_inner_knuckle_joint
      - robotiq_85_right_inner_knuckle_joint
      - robotiq_85_left_finger_tip_joint
      - robotiq_85_right_finger_tip_joint

  - name: fake_gripper_fingers_controller
    type: "position_controllers/JointTrajectoryController"
    joints:
      - robotiq_85_left_knuckle_joint
